### ISSUE TITLE
Possible reuse of an older project?

### ISSUE THREAD

**Issue by bchartier** [pi-geosolutions/vrt2rdf#1]
You may have a look at an older project I created when I was the administrator of GéoPicardie:
https://github.com/geo2france/thesaurus_builder

I updated it in 2018.
Don't know if parts of it can be reused.
Let me know.

**Comment by jeanpommier** [comment]
Hi @bchartier 
I suppose it's how I would have done it before discovering the power of VRT. Now, honestly, I prefer to put as much of the logic as possible in the VRT, configuring my source data, and having a very, very simplistic script.
Since VRT is just configuration in an XML file, it give a lot more flexibility in regards to the input data.
